name: "[CI] - DEPLOY LATEST DOCS"

on:
  workflow_call:
    workflows: [ "[CI] - Build and Test All Packages" ]
    types:
      - completed


jobs:
  docs:
    name: Deploy Storybook to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Step 2: Upload artifact to GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy Docs to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: './packages/library/storybook-static'
