name: "[CD] - DEPLOY LATEST APP"

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'The name of the artifact to deploy to GitHub Pages'
        required: false
        default: 'build-artifacts'
        type: string

jobs:
  deploy:
    name: Deploy App (Deno Deploy)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: "./packages/app"

    permissions:
      contents: read
      pages: write       # Gives access to publish to GitHub Pages
      id-token: write    # Required for authenticating to GitHub Pages

    steps:
      # Step 1: Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Step 2: Upload to Deno Deploy
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fhir-beacon-app"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "./packages/app/dist"
