name: "[CD] - APP"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    name: Deploy App (Deno Deploy)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./packages/app"

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Library
        run: "npm install --verbose"
        working-directory: ./packages/library

      - name: Build Library
        run: "npm run vite::build --verbose"
        working-directory: ./packages/library

      - name: Install App
        run: "npm install --verbose"
        working-directory: ./packages/app

      - name: Build App
        run: "pwd && npm run build --verbose"
        working-directory: ./packages/app

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fhir-beacon-app"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "./packages/app/dist"
