name: "[CD] - PUBLISH LIB"

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'build-library'
        required: false
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    # Ensure it runs only on the main branch
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      # Step 1: Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ./library

      # Step 2: Publish the library to npm
      - name: Publish Library to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish ./library --access public

      # Step 3: Create GitHub Release
      - name: Create GitHub Release
        uses: changesets/action@v1
        with:
          publish: false # Prevents duplicate npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
