name: "[CD] - Publish Library"

on:
  workflow_run:
    workflows: [ "[CI] - Build and Test All Packages" ] # Triggered by the build workflow
    types:
      - completed

jobs:
  release:
    name: Publish Library to NPM
    runs-on: ubuntu-latest

    # Ensure it runs only on the main branch
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      # Step 1: Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Step 2: Publish the library to npm
      - name: Publish Library to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish ./packages/library --access public

      # Step 3: Create GitHub Release
      - name: Create GitHub Release
        uses: changesets/action@v2
        with:
          publish: false # Prevents duplicate npm publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
