name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - '*'

permissions:
    contents: read
    pages: write
    id-token: write
    checks: write

jobs:
    publish:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: Cache node cache
                id: npm-cache
                uses: actions/cache@v3
                env:
                    cache-name: cache-npm-cache
                with:
                    # npm cache files are stored in `~/.npm` on Linux/macOS
                    path: ~/.npm
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   name: Cache node modules
                id: npm-node-modules
                uses: actions/cache@v3
                env:
                    cache-name: cache-node-modules
                with:
                    path: node_modules
                    key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-build-${{ env.cache-name }}-
                        ${{ runner.os }}-build-
                        ${{ runner.os }}-

            -   name: Cache playwright binaries
                uses: actions/cache@v3
                id: playwright-cache
                with:
                    path: |
                        ~/.cache/ms-playwright
                    key: ${{ runner.os }}-playwright-latest

            #            -   name: List the state of node modules
            #                continue-on-error: true
            #                run: npm list

            -   name: Install dependencies
                run: npm ci

            -   if: ${{steps.playwright-cache.outputs.cache-hit != 'true'}}
                name: Install playwright browsers
                run: npx playwright install --with-deps

            -   name: Run tests
                run: npm run test-all-browsers

            -   name: Publish
                run: npm run publish

            -   name: Setup Pages
                uses: actions/configure-pages@v5

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v3
                with:
                    # Upload entire repository
                    path: './storybook-static'

            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v4

            -   name: Store test results
                uses: actions/upload-artifact@v2
                with:
                    name: junit-test-results
                    path: ./results/*.xml

            -   name: Publish test results
                uses: mikepenz/action-junit-report@v3.1.0
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    report_paths: '**/results/*.xml'
