name: "[CD] - PUBLISH DOCS"

on:
  workflow_run:
    workflows: [ "[CI] - Build and Test All Packages" ] # Triggered by the build workflow
    types:
      - completed

jobs:
  deploy:
    name: Deploy Storybook (Deno Deploy)
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    # Ensure it runs only when triggered on the main branch
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      # Step 1: Download build artifacts
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      # Step 2: Upload to Deno Deploy
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fhir-beacon"
          entrypoint: "https://deno.land/std@0.217.0/http/file_server.ts"
          root: "./packages/library/storybook-static"
