name: Release Library

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'Optional name of the artifact to use'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    name: Release Library
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Ensure latest npm
        run: npm install -g npm@latest

      - name: Install Dependencies
        run: npm ci

      - name: Changeset Check
        run: npm run changeset::check

      - name: Build Library
        run: npm run build --workspace=packages/library

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: packages/library

      - name: Run Tests
        run: |
          export NODE_ICU_DATA=$PWD/node_modules/full-icu
          export LANG=en_US.UTF-8
          export LC_ALL=en_US.UTF-8
          export TZ=UTC
          npm run test --workspace=packages/library

      - name: Create Release PR or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm publish --workspace=packages/library --access public
          version: npm run release
        env:
          GITHUB_TOKEN: ${{ github.token }}
