name: "[CD] - PUBLISH LIB"

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'build-library'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js and Registry
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Debug Install
        run: |
          npm ci --workspaces --if-present
          npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release with Changesets
        uses: changesets/action@v1
        with:
          publish: npm publish --workspace=packages/library --if-present
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Debug Changesets Output
        run: |
          echo "Changeset Output:"
          ls -la .changeset
