name: "[CD] - PUBLISH LIB"

on:
  workflow_call:
    inputs:
      artifact_name:
        description: 'build-library'
        required: false
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    # Grant write permissions
    permissions:
      contents: write
      id-token: write

    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true # Use credentials for git push

      - name: Setup Node.js and Registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: |
          npm ci --workspace=packages/library
          npm run vite::build --workspace=packages/library
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release with Changesets
        uses: changesets/action@v1
        with:
          publish: npm publish --workspace=packages/library
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Debug Changesets Output
        run: |
          echo "Changeset Output:"
          ls -la .changeset

      - name: Push Tags
        run: |
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
