name: Release

on:
  workflow_run:
    workflows: [ "NonExistentWorkflow" ] # Workflow that does not exist
    types:
      - completed


jobs:
  release:
    name: Publish Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm install

      - name: Create and Version Changeset
        run: npx changeset version

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx changeset publish
